sudo: required
services:
  - docker

before_install:
  - docker build -t utpalmaity/docker-react-multicontainer -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true utpalmaity/docker-react-multicontainer npm run test -- --coverage

after_success:
  - docker build -t utpalmaity/multi-client -f ./client
  - docker build -t utpalmaity/multi-server -f ./server
  - docker build -t utpalmaity/multi-nginx -f ./nginx
  - docker build -t utpalmaity/multi-worker -f ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push utpalmaity/multi-client
  - docker push utpalmaity/multi-server
  - docker push utpalmaity/multi-nginx
  - docker push utpalmaity/multi-worker
